### ISSUE TITLE
Migration has pending actions after execution

### ISSUE THREAD

**Issue by angelxmoreno** [dereuromark/cakephp-queue#184]
when running migrations i get this:
```
/var/www/html # bin/cake migrations migrate -p Queue
using migration paths 
 - /var/www/html/vendor/dereuromark/cakephp-queue/config/Migrations
using seed paths 
 - /var/www/html/vendor/dereuromark/cakephp-queue/config/Seeds
using environment default
using adapter mysql
using database budget

 == 20150425180802 Init: migrating
 == 20150425180802 Init: migrated 0.0158s

 == 20150511062806 Fixmissing: migrating
 == 20150511062806 Fixmissing: migrated 0.0525s

 == 20150911132343 ImprovementsForMysql: migrating
Exception: Migration has pending actions after execution! in [/var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php, line 362]
2018-09-22 03:29:58 Error: [RuntimeException] Migration has pending actions after execution! in /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php on line 362
Stack Trace:
#0 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(390): Phinx\Migration\AbstractMigration->postFlightCheck('up')
#1 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(361): Phinx\Migration\Manager->executeMigration('default', Object(ImprovementsForMysql), 'up', false)
#2 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(121): Phinx\Migration\Manager->migrate('default', 20171019083500, false)
#3 /var/www/html/vendor/cakephp/migrations/src/Command/CommandTrait.php(35): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/cakephp/migrations/src/Command/Migrate.php(67): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/symfony/console/Command/Command.php(251): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/cakephp/cakephp/src/Console/Shell.php(532): Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#11 /var/www/html/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(164): Cake\Console\Shell->runCommand(Array, true, Array)
#12 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(342): Migrations\Shell\MigrationsShell->runCommand(Array, true)
#13 /var/www/html/vendor/cakephp/cakephp/src/Console/CommandRunner.php(164): Cake\Console\CommandRunner->runShell(Object(Migrations\Shell\MigrationsShell), Array)
#14 /var/www/html/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#15 {main}
```

what do i do to fix this?

**Comment by nickolaspz** [comment]
You can technically keep running the 'bin/cake migrations migrate -p Queue' command and all tables will get created.

From what I can tell, it errors out every time 'MysqlAdapter' was used.

**Comment by dereuromark** [comment]
Cant reproduce.

**Comment by garas** [comment]
Phinx v0.10 queues table operations and it requires to `save()` after `$table->changeColumn()`.

`config/Migrations/20150911132343_improvements_for_mysql.php` is missing `save()`.
