### ISSUE TITLE
Duplicate key for workerkey

### ISSUE THREAD

**Issue by challgren** [dereuromark/cakephp-queue#212]
Updated to 3.14.1 and when running ` bin/cake migrations migrate -p Queue` the following error is outputted.

```
 == 20171019083506 MigrationQueueProcessesKey: migrating
Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'workerkey' in [/Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 167]
2019-01-13 15:17:40 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'workerkey' in /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php on line 167
Stack Trace:
#0 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(167): PDO->exec('ALTER TABLE `qu...')
#1 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(126): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE `qu...')
#2 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(518): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE `qu...', Array)
#3 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(877): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('queue_processes', Object(Phinx\Db\Util\AlterInstructions))
#4 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(477): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#5 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(406): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
#6 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(477): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#7 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(144): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
#8 /Users/challgren/Projects/electric/vendor/cakephp/cakephp/src/Collection/CollectionTrait.php(51): Phinx\Db\Plan\Plan->Phinx\Db\Plan\{closure}(Object(Phinx\Db\Plan\AlterTable), 'queue_processes')
#9 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(145): Cake\Collection\Collection->each(Object(Closure))
#10 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(717): Phinx\Db\Plan\Plan->execute(Object(Migrations\CakeAdapter))
#11 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(624): Phinx\Db\Table->executeActions(true)
#12 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(683): Phinx\Db\Table->update()
#13 /Users/challgren/Projects/electric/vendor/dereuromark/cakephp-queue/config/Migrations/20171019083506_MigrationQueueProcessesKey.php(30): Phinx\Db\Table->save()
#14 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(125): MigrationQueueProcessesKey->change()
#15 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(387): Phinx\Migration\Manager\Environment->executeMigration(Object(MigrationQueueProcessesKey), 'up', false)
#16 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(361): Phinx\Migration\Manager->executeMigration('default', Object(MigrationQueueProcessesKey), 'up', false)
#17 /Users/challgren/Projects/electric/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(121): Phinx\Migration\Manager->migrate('default', 20171019083506, false)
#18 /Users/challgren/Projects/electric/vendor/cakephp/migrations/src/Command/CommandTrait.php(35): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/challgren/Projects/electric/vendor/cakephp/migrations/src/Command/Migrate.php(67): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/challgren/Projects/electric/vendor/symfony/console/Command/Command.php(255): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/challgren/Projects/electric/vendor/symfony/console/Application.php(901): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/challgren/Projects/electric/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/challgren/Projects/electric/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/challgren/Projects/electric/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/challgren/Projects/electric/vendor/cakephp/cakephp/src/Console/Shell.php(532): Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#26 /Users/challgren/Projects/electric/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(164): Cake\Console\Shell->runCommand(Array, true, Array)
#27 /Users/challgren/Projects/electric/vendor/cakephp/cakephp/src/Console/CommandRunner.php(371): Migrations\Shell\MigrationsShell->runCommand(Array, true)
#28 /Users/challgren/Projects/electric/vendor/cakephp/cakephp/src/Console/CommandRunner.php(166): Cake\Console\CommandRunner->runShell(Object(Migrations\Shell\MigrationsShell), Array)
#29 /Users/challgren/Projects/electric/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#30 {main}
```

**Comment by dereuromark** [comment]
Make sure you migrate with empty table here.

**Comment by challgren** [comment]
Yep mainly just processes I force closed.
