### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry '' for key 'workerkey'

### ISSUE THREAD

**Issue by czepter** [dereuromark/cakephp-queue#225]
After updating to the latest version i am reciving this wierd error:

```
2019-04-15 09:21:08 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'workerkey' in /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39
Stack Trace:
#0 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Database/Connection.php(334): Cake\Database\Statement\MysqlStatement->execute()
#2 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php(68): Cake\Database\Connection->Cake\Database\{closure}()
#3 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Database/Connection.php(337): Cake\Core\Retry\CommandRetry->run(Object(Closure))
#4 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Database/Query.php(219): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/ORM/Table.php(2115): Cake\Database\Query->execute()
#6 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/ORM/Table.php(2007): Cake\ORM\Table->_insert(Object(Queue\Model\Entity\QueueProcess), Array)
#7 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/ORM/Table.php(1920): Cake\ORM\Table->_processSave(Object(Queue\Model\Entity\QueueProcess), Object(ArrayObject))
#8 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/ORM/Table.php(1634): Cake\ORM\Table->Cake\ORM\{closure}()
#9 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Database/Connection.php(738): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#10 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/ORM/Table.php(1635): Cake\Database\Connection->transactional(Object(Closure))
#11 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/ORM/Table.php(1921): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#12 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/ORM/Table.php(1949): Cake\ORM\Table->save(Object(Queue\Model\Entity\QueueProcess), Object(ArrayObject))
#13 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/dereuromark/cakephp-queue/src/Model/Table/QueueProcessesTable.php(129): Cake\ORM\Table->saveOrFail(Object(Queue\Model\Entity\QueueProcess))
#14 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php(667): Queue\Model\Table\QueueProcessesTable->add('3346', '10515f3aa59332d...')
#15 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php(153): Queue\Shell\QueueShell->_initPid()
#16 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Console/Shell.php(518): Queue\Shell\QueueShell->runworker()
#17 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Console/CommandRunner.php(367): Cake\Console\Shell->runCommand(Array, true)
#18 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/vendor/cakephp/cakephp/src/Console/CommandRunner.php(162): Cake\Console\CommandRunner->runShell(Object(Queue\Shell\QueueShell), Array)
#19 /var/www/vhosts/minutes-crm.de/my.minutes-crm.de/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#20 {main}
```

### steps tried to fix
deleted all queue_* related db files
composer clear cache
composer update
bin/cake migrations migrate -p Queue
bin/cake queue runworker

### enviroment
php 7.3.4
mysql 5.7.25

**Comment by dereuromark** [comment]
See https://github.com/dereuromark/cakephp-queue/tree/master/docs#multi-server-setup
make sure you got a worker key set up as per docs here. Usually, there should always be one based on the SERVER_NAME data.
