### ISSUE TITLE
Trying to update for CakePHP 3.8

### ISSUE THREAD

**Issue by hectorviov** [dereuromark/cakephp-queue#237]
After updating the composer version for 4.0.1 because I updated to CakePHP 3.8 i can't migrate anymore. I'm using a different connection for the queue DB.

I added the Configure::load('app_queue'); line to my bootstrap.

Changed the Plugin load to Application's file bootstrap using:  $this->addPlugin('Queue', ['routes' => true]);

After trying the "bin/cake migrations migrate -p Queue" for the new database changes I see that it tries to use the default connection instead of the one I used in my app_queue.php file in the 'connection' parameter. Also changed 'multiserver' to true (don't know if I need this).

Please help...

**Comment by dereuromark** [comment]
what is the one you are using in your app_queue file?

**Comment by hectorviov** [comment]
It is 'connection' => 'queue',

**Comment by dereuromark** [comment]
Then you need to find out what migrations have been run and which didnt.
You can manually set some to "migrated" if needed.

**Comment by hectorviov** [comment]
The thing is that it creates new tables on the default database, instead of altering or creating on the 'queue' database. This is because my default DB uses postgresql and queue uses mysql. This is my output:

```
Deprecated Error: Plugin::load() is deprecated. Use Application::addPlugin() instead. This method will be removed in 4.0.0. - D:\Documents\cakephpapp\config\bootstrap_cli.php, line: 33
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in [D:\Documents\cakephpapp\vendor\cakephp\cakephp\src\Core\functions.php, line 311]

Deprecated Error: Plugin::load() is deprecated. Use Application::addPlugin() instead. This method will be removed in 4.0.0. - D:\Documents\cakephpapp\config\bootstrap_cli.php, line: 38
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php. in [D:\Documents\cakephpapp\vendor\cakephp\cakephp\src\Core\functions.php, line 311]

using migration paths
 - D:\Documents\cakephpapp\vendor\dereuromark\cakephp-queue\config\Migrations
using seed paths
 - D:\Documents\cakephpapp\vendor\dereuromark\cakephp-queue\config\Seeds
using environment default
using adapter pgsql
using database appdb

 == 20150425180802 Init: migrating
 == 20150425180802 Init: migrated 0.0531s

 == 20150511062806 Fixmissing: migrating
 == 20150511062806 Fixmissing: migrated 0.0152s

 == 20150911132343 ImprovementsForMysql: migrating
 == 20150911132343 ImprovementsForMysql: migrated 0.0093s

 == 20161319000000 IncreaseDataSize: migrating

'SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier is not allowed for type "text"'

RuntimeException: Migration has pending actions after execution! in D:\Documents\cakephpapp\vendor\robmorgan\phinx\src\Phinx\Migration\AbstractMigration.php:362
Stack trace:
#0 D:\Documents\cakephpapp\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php(394): Phinx\Migration\AbstractMigration->postFlightCheck('up')
#1 D:\Documents\cakephpapp\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php(365): Phinx\Migration\Manager->executeMigration('default', Object(IncreaseDataSize), 'up', false)
#2 D:\Documents\cakephpapp\vendor\robmorgan\phinx\src\Phinx\Console\Command\Migrate.php(122): Phinx\Migration\Manager->migrate('default', '20171019083506', false)
#3 D:\Documents\cakephpapp\vendor\cakephp\migrations\src\Command\CommandTrait.php(35): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 D:\Documents\cakephpapp\vendor\cakephp\migrations\src\Command\Migrate.php(67): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 D:\Documents\cakephpapp\vendor\symfony\console\Command\Command.php(264): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 D:\Documents\cakephpapp\vendor\symfony\console\Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 D:\Documents\cakephpapp\vendor\symfony\console\Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 D:\Documents\cakephpapp\vendor\symfony\console\Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 D:\Documents\cakephpapp\vendor\cakephp\migrations\src\Shell\MigrationsShell.php(109): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 D:\Documents\cakephpapp\vendor\cakephp\cakephp\src\Console\Shell.php(532): Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#11 D:\Documents\cakephpapp\vendor\cakephp\migrations\src\Shell\MigrationsShell.php(165): Cake\Console\Shell->runCommand(Array, true, Array)
#12 D:\Documents\cakephpapp\vendor\cakephp\cakephp\src\Console\CommandRunner.php(384): Migrations\Shell\MigrationsShell->runCommand(Array, true)
#13 D:\Documents\cakephpapp\vendor\cakephp\cakephp\src\Console\CommandRunner.php(162): Cake\Console\CommandRunner->runShell(Object(Migrations\Shell\MigrationsShell), Array)
#14 D:\Documents\cakephpapp\bin\cake.php(12): Cake\Console\CommandRunner->run(Array)
#15 {main}
using migration paths
 - D:\Documents\cakephpapp\vendor\dereuromark\cakephp-queue\config\Migrations
using seed paths
 - D:\Documents\cakephpapp\vendor\dereuromark\cakephp-queue\config\Seeds
Writing dump file `D:\Documents\cakephpapp\vendor\dereuromark\cakephp-queue\config\Migrations\schema-dump-default.lock`...
Dump file `D:\Documents\cakephpapp\vendor\dereuromark\cakephp-queue\config\Migrations\schema-dump-default.lock` was successfully written
```

**Comment by dereuromark** [comment]
You then need to copy them over to project level and not run migrations on the plugin itself.
This is custom to your app and cannot be handled inside the plugin IMO.

**Comment by hectorviov** [comment]
I had exactly this error before and just decided to use mysql for database and then I don't get the  `'SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier is not allowed for type "text"'` error. But migrating after updating to 4.0.1 it doesn't use the correct connection. 

I'll try to copy migrations to project level, and check if it works.

**Comment by hectorviov** [comment]
Ok, so I got it to migrate correctly now, but when I try to run `bin/cake queue runworker` it gets me an error saying 

` SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'workerkey'`

which I get is an error where it is not getting any workerkey. After reading the docs, how should I set the `env('SERVER_NAME')`?

**Comment by dereuromark** [comment]
Make sure you have a valid server name set for ENV, as documented.
Without it, you would have to have your own custom schema, instead of the one being used for uniqueness check.
