### ISSUE TITLE
 General error: 1364 Field 'workerkey' doesn't have a default value

### ISSUE THREAD

**Issue by aeanez** [dereuromark/cakephp-queue#337]
Im getting this error when manually running the worker for version 3

```
Exception: SQLSTATE[HY000]: General error: 1364 Field 'workerkey' doesn't have a default value in [/code/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, 
line 39]
2022-08-13 09:17:28 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'workerkey' doesn't have a default value in /code/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39
Stack Trace:
#0 /code/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 /code/vendor/cakephp/cakephp/src/Database/Connection.php(315): Cake\Database\Statement\MysqlStatement->execute()
#2 /code/vendor/cakephp/cakephp/src/Database/Query.php(214): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#3 /code/vendor/cakephp/cakephp/src/ORM/Table.php(1929): Cake\Database\Query->execute()
#4 /code/vendor/cakephp/cakephp/src/ORM/Table.php(1823): Cake\ORM\Table->_insert(Object(Queue\Model\Entity\QueueProcess), Array)
#5 /code/vendor/cakephp/cakephp/src/ORM/Table.php(1736): Cake\ORM\Table->_processSave(Object(Queue\Model\Entity\QueueProcess), Object(ArrayObject))
#6 /code/vendor/cakephp/cakephp/src/ORM/Table.php(1459): Cake\ORM\Table->Cake\ORM\{closure}()
#7 /code/vendor/cakephp/cakephp/src/Database/Connection.php(682): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#8 /code/vendor/cakephp/cakephp/src/ORM/Table.php(1460): Cake\Database\Connection->transactional(Object(Closure))
#9 /code/vendor/cakephp/cakephp/src/ORM/Table.php(1737): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#10 /code/vendor/cakephp/cakephp/src/ORM/Table.php(1765): Cake\ORM\Table->save(Object(Queue\Model\Entity\QueueProcess), Object(ArrayObject))
#11 /code/vendor/dereuromark/cakephp-queue/src/Model/Table/QueueProcessesTable.php(94): Cake\ORM\Table->saveOrFail(Object(Queue\Model\Entity\QueueProcess))
#12 /code/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php(510): Queue\Model\Table\QueueProcessesTable->add('172')
#13 /code/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php(127): Queue\Shell\QueueShell->_initPid()
#14 /code/vendor/cakephp/cakephp/src/Console/Shell.php(493): Queue\Shell\QueueShell->runworker()
#15 /code/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#16 /code/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#17 /code/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#18 /code/bin/cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#19 {main}
```

**Comment by aeanez** [comment]
I have fix the problem adding a line to the QueueProcessesTable.php file, it works but not sure the menaning of that column, does anyone know?

/**
* @param string $pid
*
* @return int
*/
public function add($pid) {
  $queueProcess = $this->newEntity([
	  'pid' => $pid,
	  'workerkey' => 'test' //<- Line added
  ]);
  
  $this->saveOrFail($queueProcess);
  
  return $queueProcess->id;
}

**Comment by aeanez** [comment]
Looks like this was fixed in newer versions!!
