### ISSUE TITLE
Migration not working on fresh installation

### ISSUE THREAD

**Issue by oresch** [dereuromark/cakephp-queue#350]
I just created a new fresh project and want to add you queue plugin as described in your docs
`composer create-project --prefer-dist cakephp/app:~4.0 my_app_name`
`composer require dereuromark/cakephp-queue`
than added in `src/Application.php` the needed ref and finally run the migration command:

```
$ bin/cake migrations migrate -p Queue
using migration paths
 - C:\dev\gitlab\eta\vendor\dereuromark\cakephp-queue\config\Migrations
using seed paths
 - C:\dev\gitlab\eta\vendor\dereuromark\cakephp-queue\config\Seeds
using environment default
using adapter mysql
using database eta
ordering by creation time
InvalidArgumentException: Duplicate migration - "C:\dev\gitlab\eta\vendor\dereuromark\cakephp-queue\config\Migrations\20150511062806_fixmissing.php" has the same version as "2147483647" in C:\dev\gitlab\eta\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php:782
Stack trace:
#0 C:\dev\gitlab\eta\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php(313): Phinx\Migration\Manager->getMigrations('default')
#1 C:\dev\gitlab\eta\vendor\robmorgan\phinx\src\Phinx\Console\Command\Migrate.php(122): Phinx\Migration\Manager->migrate('default', NULL, false)
#2 C:\dev\gitlab\eta\vendor\cakephp\migrations\src\Command\Phinx\CommandTrait.php(37): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\dev\gitlab\eta\vendor\cakephp\migrations\src\Command\Phinx\Migrate.php(85): Migrations\Command\Phinx\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\dev\gitlab\eta\vendor\symfony\console\Command\Command.php(312): Migrations\Command\Phinx\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\dev\gitlab\eta\vendor\symfony\console\Application.php(1020): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\dev\gitlab\eta\vendor\symfony\console\Application.php(312): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Phinx\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\dev\gitlab\eta\vendor\symfony\console\Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\dev\gitlab\eta\vendor\cakephp\migrations\src\Command\MigrationsCommand.php(126): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\dev\gitlab\eta\vendor\cakephp\cakephp\src\Console\BaseCommand.php(189): Migrations\Command\MigrationsCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#10 C:\dev\gitlab\eta\vendor\cakephp\migrations\src\Command\MigrationsCommand.php(198): Cake\Console\BaseCommand->run(Array, Object(Cake\Console\ConsoleIo))
#11 C:\dev\gitlab\eta\vendor\cakephp\cakephp\src\Console\CommandRunner.php(334): Migrations\Command\MigrationsCommand->run(Array, Object(Cake\Console\ConsoleIo))
#12 C:\dev\gitlab\eta\vendor\cakephp\cakephp\src\Console\CommandRunner.php(172): Cake\Console\CommandRunner->runCommand(Object(Migrations\Command\MigrationsMigrateCommand), Array, Object(Cake\Console\ConsoleIo))
#13 C:\dev\gitlab\eta\bin\cake.php(12): Cake\Console\CommandRunner->run(Array)
#14 {main}
```
In the DB there are no *phinx* tables or old *queue* tables - so a really fresh install from scratch.

Any hints about how to go on? Older projects are working fine - but there I'm coming from older queue versions...

tx

**Comment by dereuromark** [comment]
Can you reproduce this using devilbox and Linux based?
As I cannot.. weird

**Comment by oresch** [comment]
Ok, the output above came from GitBash under W11; I tested now in my Docker container - voilà, it's running ;-) 
So some strange Win and gitbash confusions. 
So you can close this case - mabye with a small hint in the readme to use native shells and not this gitbash stuff :-)

Thx

**Comment by dereuromark** [comment]
Sure, feel free to PR any wording here.
Thx for the feedback
