### ISSUE TITLE
Error loading custom tasks Cake 3

### ISSUE THREAD

**Issue by leighmackay** [dereuromark/cakephp-queue#48]
Hello,

Having issue loading custom tasks for Cake 3.0.8.

Created custom task `Shell/Task/QueueExample2Task.php` it shows up when running  `./bin/cake Queue.Queue` 

```
Available Tasks:
	* Example2
	* Email
	* Example
	* Execute
	* LongExample
	* RetryExample
	* SuperExample
```

But when running `./bin/cake Queue.Queue add Example2` the follow error shows up in terminal.

```
Exception: Task class QueueExample2 could not be found. in [/Users/lmackay/Desktop/test_app/vendor/cakephp/cakephp/src/Console/TaskRegistry.php, line 70]
2015-07-19 07:37:19 Error: [Cake\Console\Exception\MissingTaskException] Task class QueueExample2 could not be found.
Exception Attributes: array (
  'class' => 'QueueExample2',
  'plugin' => NULL,
)
Stack Trace:
#0 /Users/lmackay/Desktop/test_app/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(90): Cake\Console\TaskRegistry->_throwMissingClassError('QueueExample2', NULL)
#1 /Users/lmackay/Desktop/test_app/vendor/cakephp/cakephp/src/Console/Shell.php(441): Cake\Core\ObjectRegistry->load('QueueExample2', Array)
#2 /Users/lmackay/Desktop/test_app/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php(119): Cake\Console\Shell->__get('QueueExample2')
#3 [internal function]: Queue\Shell\QueueShell->add('Example2')
#4 /Users/lmackay/Desktop/test_app/vendor/cakephp/cakephp/src/Console/Shell.php(380): call_user_func_array(Array, Array)
#5 /Users/lmackay/Desktop/test_app/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(204): Cake\Console\Shell->runCommand(Array, true)
#6 /Users/lmackay/Desktop/test_app/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(175): Cake\Console\ShellDispatcher->_dispatch()
#7 /Users/lmackay/Desktop/test_app/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(126): Cake\Console\ShellDispatcher->dispatch()
#8 /Users/lmackay/Desktop/test_app/bin/cake.php(33): Cake\Console\ShellDispatcher::run(Array)
#9 {main}
```

it seems that it's trying to load the task relative to the Plugin path. Putting the file in `dereuromark/cakephp-queue/src/Shell/Task/QueueExample2Task.php` makes it work.

Looked into the error a bit further and tasks are loading in via `/cakephp/src/Core/ObjectRegistry.php`'s load method. It takes a $config key called "className" and can alias classes `\App\Shell\Task\QueueExample2Task` so maybe it needs to do that for custom tasks in the `QueueShell->initialize()`

Or maybe I'm just not using this plugin right, which would be great. It looks like a very good plugin, thank you.

**Comment by leighmackay** [comment]
it was just a namespace issue! all fixed.
